version: '3.5'

services:
  web:
    image: docker-hub.dev.siap.id/guru-berbagi/web-devel:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    ports:
      - 7071:80